# Locked source archives are shared across build directories.
set(MOORHUHN_DEPENDENCY_CACHE "${PROJECT_SOURCE_DIR}/build/dependencies" CACHE PATH
    "Archive and source cache for pinned dependencies")
option(MOORHUHN_OFFLINE "Reject downloads; use the dependency cache only" OFF)
file(READ "${CMAKE_CURRENT_LIST_DIR}/dependencies.lock.json" _moorhuhn_lock)

function(moorhuhn_dependency_source name output)
    foreach(field IN ITEMS url archive archive_root sha256 license_file license_sha256)
        string(JSON ${field} GET "${_moorhuhn_lock}" dependencies "${name}" "${field}")
    endforeach()
    file(MAKE_DIRECTORY "${MOORHUHN_DEPENDENCY_CACHE}/archives")
    file(LOCK "${MOORHUHN_DEPENDENCY_CACHE}/populate.lock" GUARD FUNCTION TIMEOUT 120)
    set(archive_path "${MOORHUHN_DEPENDENCY_CACHE}/archives/${archive}")
    if(EXISTS "${archive_path}")
        file(SHA256 "${archive_path}" actual_hash)
        if(NOT actual_hash STREQUAL sha256)
            message(FATAL_ERROR "Cached ${name} archive has the wrong SHA-256: ${archive_path}")
        endif()
    elseif(MOORHUHN_OFFLINE)
        message(FATAL_ERROR "Offline cache is missing ${archive_path}")
    else()
        message(STATUS "Downloading pinned ${name}")
        file(DOWNLOAD "${url}" "${archive_path}" EXPECTED_HASH "SHA256=${sha256}"
            TLS_VERIFY ON STATUS download_status)
        list(GET download_status 0 download_code)
        if(NOT download_code EQUAL 0)
            message(FATAL_ERROR "Download failed for ${name}: ${download_status}")
        endif()
    endif()
    set(source_parent "${MOORHUHN_DEPENDENCY_CACHE}/sources/${name}-${sha256}")
    set(source "${source_parent}/${archive_root}")
    if(NOT EXISTS "${source_parent}/.complete")
        file(MAKE_DIRECTORY "${source_parent}")
        file(ARCHIVE_EXTRACT INPUT "${archive_path}" DESTINATION "${source_parent}")
        file(WRITE "${source_parent}/.complete" "${sha256}\n")
    endif()
    file(SHA256 "${source}/${license_file}" actual_license_hash)
    if(NOT actual_license_hash STREQUAL license_sha256)
        message(FATAL_ERROR "License hash mismatch for ${name}")
    endif()
    set(${output} "${source}" PARENT_SCOPE)
endfunction()

if(MOORHUHN_BUILD_SDL_ADAPTER)
    moorhuhn_dependency_source(sdl3 sdl_source)
    moorhuhn_dependency_source(sdl3_mixer mixer_source)

    # Runtime libraries live next to the application, with MP3 decoding built into the mixer.
    set(BUILD_SHARED_LIBS ON CACHE BOOL "" FORCE)
    set(SDL_SHARED ON CACHE BOOL "" FORCE)
    set(SDL_STATIC OFF CACHE BOOL "" FORCE)
    set(SDL_FRAMEWORK OFF CACHE BOOL "" FORCE)
    set(SDL_TEST_LIBRARY OFF CACHE BOOL "" FORCE)
    set(SDL_TESTS OFF CACHE BOOL "" FORCE)
    set(SDL_INSTALL OFF CACHE BOOL "" FORCE)
    set(SDL_EXAMPLES OFF CACHE BOOL "" FORCE)
    set(SDL_WERROR OFF CACHE BOOL "" FORCE)
    add_subdirectory("${sdl_source}" "${CMAKE_BINARY_DIR}/_deps/sdl" SYSTEM EXCLUDE_FROM_ALL)

    set(SDLMIXER_VENDORED ON CACHE BOOL "" FORCE)
    set(SDLMIXER_DEPS_SHARED ON CACHE BOOL "" FORCE)
    set(SDLMIXER_STRICT ON CACHE BOOL "" FORCE)
    set(SDLMIXER_INSTALL OFF CACHE BOOL "" FORCE)
    set(SDLMIXER_TESTS OFF CACHE BOOL "" FORCE)
    set(SDLMIXER_EXAMPLES OFF CACHE BOOL "" FORCE)
    set(SDLMIXER_WERROR OFF CACHE BOOL "" FORCE)
    foreach(codec IN ITEMS AIFF WAVE VOC AU GME MOD FLAC MIDI VORBIS_STB VORBIS_VORBISFILE VORBIS_TREMOR WAVPACK OPUS)
        set(SDLMIXER_${codec} OFF CACHE BOOL "" FORCE)
    endforeach()
    set(SDLMIXER_MP3 ON CACHE BOOL "" FORCE)
    set(SDLMIXER_MP3_MPG123 OFF CACHE BOOL "" FORCE)
    set(SDLMIXER_MP3_DRMP3 ON CACHE BOOL "" FORCE)
    add_subdirectory("${mixer_source}" "${CMAKE_BINARY_DIR}/_deps/mixer" SYSTEM EXCLUDE_FROM_ALL)

    set(MOORHUHN_RUNTIME_TARGETS SDL3-shared SDL3_mixer-shared)
    # Game modules remain part of the executable.
    set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
endif()
